### ISSUE TITLE
Connect using Bluetooth address instead of COM port

### ISSUE THREAD

**Issue by gazialankus** [hybridgroup/cylon-sphero#59]
I came to Cylon since in a quick try I could not drive more than one SPRK+s using [sphero.js](https://github.com/orbotix/sphero.js). I'm using Windows 10. 

However, Cylon docs suggest connecting using the COM port. I could not figure out how to find the COM port that the paired SPRK+ is connected to in Windows 10. 

In sphero.js, I could connect to the SPRK+ like this using the BLE address: 

`sprkp = sphero("da:82:11:29:94:98");
`

Also in [cylon-sphero-ble](https://github.com/hybridgroup/cylon-sphero-ble) you can connect using the BLE address (but it did not work for my SPRK+):

`Cylon.robot({
  connections: {
    bluetooth: { adaptor: 'central', uuid: 'cc360e85785e', module: 'cylon-ble'}
  },
`

However with cylon-sphero I seem to have to use the COM port, which I'm not able to find. 

Is there a way to connect to my SPRK+ with cylon-sphero using the BLE address?

**Comment by gazialankus** [comment]
Oops, sorry. It seems I can just use [cylon-sphero-ble](https://github.com/hybridgroup/cylon-sphero-ble) with SPRK+.

**Comment by yordan94** [comment]
Good afternoon.
Excuse me Mr. Alankus, I am trying to connect my Sphero SPRK+ using cylon.js but I didn't have succeeded.
Did you have succeeded connecting your Sphero SPRK+ with your pc using Cylon.js?

**Comment by gazialankus** [comment]
Here's what I ended up doing, hope it helps: https://github.com/hybridgroup/cylon-sphero-ble/issues/14

**Comment by yordan94** [comment]
So, did you use Sphero.js to connect your SPRK+ with your JS Application?
I tried to do that, but I think that I had an issue with my Bluetooth connection, because in my ports connection my sphero hasn't a com port assigned.

How did you assign a port to your Sphero connection?
What Windows' version did you use for your example?

The next is the code to connect the Sphero by a port connection.

var sphero = require("sphero"),
    orb = sphero("/dev/rfcomm0"); // change port accordingly

orb.connect(function() {
  // Sphero's connected!
  // do some cool stuff here!
});

Thank you for your response.

**Comment by gazialankus** [comment]
As far as I remember, I used it like a bb8 with the Bluetooth address, not with a COM port. Let me know if that does not work.

**Comment by yordan94** [comment]
I tried to find the Bluetooth address but in my PC my Sphero didn't have a Bluetooth address assigned.
How did you get the Bluetooth address?

Actually, I used a Bluetooth command line to try to find some helpful information but it didn't show anything.
